spring:
  application:
    name: StudyLangChain4J
  profiles:
    include: secrets
langchain4j:
  open-ai:
    chat-model:
      model-name: qwen-turbo
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
#      model-name: qwen2.5
logging:
  level:
    root: debug