spring:
  application:
    name: StudyLangChain4J
  profiles:
    include: secrets
langchain4j:
  open-ai:
    chat-model:
      # model-name: qwen-turbo
      # 图片理解能力的大模型
      model-name: qwen-vl-max
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      # model-name: qwen2.5
logging:
  level:
    root: debug