spring:
  application:
    name: StudyLangChain4J
  profiles:
    include: secrets
# 解决Controller中返回`Flux<String>`乱码问题
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
langchain4j:
  open-ai:
    chat-model:
      model-name: grok-beta
      base-url: https://api.x.ai/v1
    embedding-model:
      model-name: text-embedding-v3
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
#logging:
#  level:
#    root: debug